#!/bin/sh
#
#       script to install nbd
#

logfile="/var/log/zhicloud_install.log"
#install_path="/home/zhicloud/lib"
install_path=$(cd "$(dirname "$0")";cd ..;pwd)


##########################################################
#step 1:
#install nbd 3.3
#

echo "start install nbd"
echo "start install nbd" >> $logfile

cd ${install_path}/lib
if ! tar jxf nbd-3.3.tar.bz2 2>>$logfile
then
	echo "tar nbd-3.3 fail"
	echo "tar nbd-3.3 fail" >> $logfile
	exit 1
else
	echo "tar nbd-3.3 success"
	echo "tar nbd-3.3 success" >> $logfile
    
fi

cd nbd-3.3
if ! ./configure 2>>$logfile
then
	echo "configure nbd-3.3 fail"
	echo "configure nbd-3.3 fail" >> $logfile
	exit 1
else
	echo "configure nbd-3.3 success"
	echo "configure nbd-3.3 success" >> $logfile
fi

if ! make 2>>$logfile
then
	echo "make nbd-3.3 fail"
	echo "make nbd-3.3 fail" >> $logfile
	exit 1
else
	echo "make nbd-3.3 success"
	echo "make nbd-3.3 success" >> $logfile
fi

if ! make install 2>>$logfile
then
	echo "make install nbd-3.3 fail"
	echo "make install nbd-3.3 fail" >> $logfile
	exit 1
else
	echo "make install nbd-3.3 success"
	echo "make install nbd-3.3 success" >> $logfile
fi

echo "completed install nbd"
echo "completed install nbd" >> $logfile
