#!/bin/sh
#
#       script to init libvirt
#

logfile="/var/log/zhicloud_install.log"
#install_path="/home/zhicloud/lib"
install_path=$(cd "$(dirname "$0")";cd ..;pwd)

echo "init libvirt... "

chkconfig cgconfig on 2>>$logfile
service cgconfig start 2>>$logfile
echo "start config vnc&qemu..."
sed -i 's/#vnc_listen = "0.0.0.0"/vnc_listen = "0.0.0.0"/g' /etc/libvirt/qemu.conf
echo "set config vnc_listen = 0.0.0.0"
sed -i 's/#user = "root"/user = "root"/g' /etc/libvirt/qemu.conf
echo "set config user = root"
sed -i 's/#group = "root"/group = "root"/g' /etc/libvirt/qemu.conf
echo "set config group = root"
echo "start service libvirtd..."
service libvirtd start 2>>$logfile
